//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lks_jadwal_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailSchedule
    {
        public int detailId { get; set; }
        public int scheduleId { get; set; }
        public int studentId { get; set; }
    
        public virtual HeaderSchedule HeaderSchedule { get; set; }
        public virtual Student Student { get; set; }
    }
}
