//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lks_jadwal_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.DetailSchedules = new HashSet<DetailSchedule>();
        }
    
        public int studentId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string gender { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public string noHp { get; set; }
        public int userId { get; set; }
        public Nullable<int> classId { get; set; }
        public byte[] photo { get; set; }
    
        public virtual Class Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailSchedule> DetailSchedules { get; set; }
        public virtual user user { get; set; }
    }
}
